---
- name: copy sample file to remote
  hosts: all
  gather_facts: false
  ignore_unreachable: true
  ignore_errors: true
  tasks:
  - name: coping file to remote ...
    copy:
      src: ./sample.txt
      dest: /home/ravi
      follow: yes
    notify: copy msg
  
  handlers:
  - name: copy msg
    debug:
      msg: copied successfully!